version: '3'
services:
  db:
    image: postgres:14
    container_name: whaticket-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dmaisbrasil2024
      POSTGRES_DB: whaticket
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  whaticket:
    build: .
    container_name: whaticket-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:dmaisbrasil2024@db:5432/whaticket
      JWT_SECRET: dmaisbrasil2024
      FRONTEND_URL: http://177.153.58.60:3000
      BACKEND_URL: http://177.153.58.60:3000
      PORT: "3000"

volumes:
  postgres_data:
